version: '3.9'

services:
  web:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo?createDatabaseIfNotExist=true
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - todo-db:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=mysql --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    restart: on-failure

volumes:
  todo-db:

